### ISSUE TITLE
TCP Server File Transfer Of BLOB (e.g. 5 MB) file Blocks

### ISSUE THREAD

**Issue by sbernin** [vovkos/ioninja-issues#16]
Hi,

I tried to transmit a BLOB of 5 MB (generated with dd) through a TCP Server created with IO Ninja on my PC (connected by Ethernet) to a WiFi eval board connected to my WiFi. The received stream is then put onto UART and I can read it from any UART Terminal (IO Ninja, TeraTerm, etc.)
The transmission stops after a few hundred bytes.
I tried this with two modules (Dialog DA16200 and Telit WE310F5) and for the Dialog module, there is no chance to get any further progress. For the Telit module, sending any message from the Module towards the TCP Server allows the upload to continue but only for another chunk.
I tested it with Netcat and it worked just fine for both modules.
Therefore, I assume the bug is on the IO Ninja's side TCP stack implementation.

Best regards
Simon

**Comment by vovkos** [comment]
Hi Simon,

Thank you for the bug report, and apologies for the late reply. 

First, let's make sure we are on the same page.

1) You run the latest IO Ninja 3.15.1-a, correct? Which platform do you use (Windows/Linux/macOS)?

2) Then you open a TCP Server session and connect to it from your module.

3) Then you choose the Transmit/File, browse for a file, and click Send:

![image](https://user-images.githubusercontent.com/1272029/111946700-f459cf80-8b16-11eb-8ada-7c97ee1d1688.png)

4) Then, after a few kilobytes, the transmission stops. 

Everything correct?

If yes, things to try:

1) If you connect to the TCP Server with ``netcat``, do you experience the same issue?

2) Also, if you capture this TCP transmission with Wireshark, do you see any abnormalities? Like, missing ACKs, lots of retransmissions, empty TCP windows, stuff like that.

Thank you!

**Comment by vovkos** [comment]
Hello again Simon,

I think I remember similar symptoms we experienced locally here in our office. Our network module was connecting to a TCP Server, then file transmit got occasionally stuck due to the zeroed-TCP-window and TCP server not catching the event of TCP window recovery. The issue was fixed but not published yet. This commit takes care of it:

https://github.com/vovkos/ioninja-scripts/commit/41ee4ce6cb10289920d72deb2ab859f772fa2998

You can download the latest commit from the master branch, and then simply overwrite your ``scripts/plugins/TcpServer`` folder with the new files.

Let me know if it works for you.

**Comment by sbernin** [comment]
Hi Vladimir,

yes, that was the version used and those were the steps applied and I used Windows 10.
I did not try the other suggested steps with Wireshark and netcat, since you posted this fix... **and it works!** Thanks!

Dialog uses your tool in their documentation and confirmed the behavior on their side. I suggest releasing more frequently! ;-)

Best regards
Simon
