### ISSUE TITLE
[macOS] Does not detect pseudo-terminals

### ISSUE THREAD

**Issue by kubark42** [vovkos/ioninja-issues#18]
I use socat to create a pseudo-terminal on my Mac.

```
% socat -d -d pty,echo=0,raw pty,echo=0,raw

2021/08/02 09:56:56 socat[31905] N PTY is /dev/ttys003
2021/08/02 09:56:56 socat[31905] N PTY is /dev/ttys005
2021/08/02 09:56:56 socat[31905] N starting data transfer loop with FDs [5,5] and [7,7]
```

This makes a pseduo-terminal with endpoints given by the macOS subsystem. Using `screen` I can connect to these tty pseudo-devices (`/dev/ttys003` and `/dev/ttys005` in the above example)and send data back and forth between the two.

However, IO-Ninja does not see them and so cannot connect.

The issues at https://github.com/vovkos/ioninja-issues/issues/13 is in a similar vein, where there are no associated `IOSerialBSDClient` entries in the ioreg device tree.

**Comment by vovkos** [comment]
The **Serial** plugin of IO Ninja doesn't recognize those pseudo-terminals as serial ports -- because they are not! On Darwin-based OS-es, IO Ninja enumerates serial ports by listing IOKit services matching ``kIOSerialBSDServiceValue`` -- apparently, these pseudo-terminals are not registered as ones. Trying to open these pseudo-terminals *by name* from the **Serial** plugin will most likely fail, too -- for this to work, they must respond properly to ``termios`` IOCTLs for setting baud rate, parity, etc.

However! You still can work with those pseudo-terminals in IO Ninja by using the **File Stream** session. Just type in the file name ``/dev/ttys003``, specify the access mode as ``Read/Write`` and open the device. All incoming bytes will be printed in log, and you will be able to use the "Transmit" or "Script" pane to send bytes.

**Comment by vovkos** [comment]
Just tried to do it on my Mac-mini running Mojave and it worked. Just in case, the **File Stream** session is in the group called "Other Sessions".

**Comment by kubark42** [comment]
Thanks!

The one downside of this approach is that the user has to know the serial port naming convention for pseudo-ports, but since that's printed as part of the `socat` output it's not a huge burden.
