### ISSUE TITLE
Erroneous dependency in rpm package

### ISSUE THREAD

**Issue by ghost** [vovkos/ioninja-issues#4]
The ioninja 64bit rpm package has an erroneous libjancy ependency. This affects Fedora 28 and CentOS 7.5 (and previous versions).

Installation attempt on Fedora 28:
```
# rpm -Uvh ioninja-3.8.7-linux-amd64.rpm
error: Failed dependencies:
        libjancy.so.1.8()(64bit) is needed by ioninja-3.8.7-1.amd64
```

The libjancy shared library is included in the ioninja package:
```
# rpm -qlp ioninja-3.8.7-linux-amd64.rpm | grep libjancy
/usr/lib/libjancy.so
/usr/lib/libjancy.so.1.8
/usr/lib/libjancy.so.1.8.2
```

Workaround:
Disable dependency check while installing the rpm package:
```
# rpm -Uvh --nodeps ioninja-3.8.7-linux-amd64.rpm
```

**Comment by vovkos** [comment]
This bogus dependency was added by the CPack RPM generator because of libjancy.so.x.x was not made executable. It is now, but eventually, I decided to disable the RPM dependency calculation completely with 
``set (CPACK_RPM_PACKAGE_AUTOREQ OFF)``

I'm afraid, dependencies can only be properly calculated when and if we provide per-distro packages (e.g., one for Arch, one for Ubuntu/Mint/derivatives, one for Fedora, etc). Until then, we are going to have DEB and RPM packages *without* auto-calculated dependencies.

Actually, if QT5 is installed -- and it's there on most modern distros -- ioninja should work.

The RPM in the new 3.9.0 has no dependencies, so the above issue should be fixed. Please re-open if it's not.
